const Departamentos = [
    {
        nombre: 'Atlántida',
        municipios: [
            'La Ceiba',
            'El Porvenir',
            'Tela',
            'Jutiapa',
            'La Masica',
            'San Francisco',
            'Arizona',
            'Esparta'
        ]
    },
    {
        nombre: 'Choluteca', 
        municipios: [
            'Choluteca',
            'Apacilagua',
            'Concepción de María',
            'Duyure',
            'El Corpus',
            'El Triunfo',
            'Marcovia',
            'Morolica',
            'Namasigüe',
            'Orocuina',
            'Pespire',
            'San Antonio de Flores',
            'San Isidro',
            'San José',
            'San Marcos de Colón',
            'Santa Ana de Yusguare'
        ]
    },
    {
        nombre: 'Colón',
        municipios: [
            'Trujillo',
            'Balfate',
            'Iriona',
            'Limón',
            'Sabá',
            'Santa Fe',
            'Santa Rosa de Aguán',
            'Sonaguera',
            'Tocoa',
            'Bonito Oriental'
        ]
    },
    {
        nombre: 'Comayagua',
        municipios: [
            'Comayagua',
            'Ajuterique',
            'El Rosario',
            'Esquías',
            'Humuya',
            'La Libertad',
            'Lamaní',
            'La Trinidad',
            'Lejamaní',
            'Meámbar',
            'Minas de Oro',
            'Ojos de Agua',
            'San Jerónimo',
            'San José de Comayagua',
            'San José del Potrero',
            'San Luis',
            'San Sebastián',
            'Siguatepeque',
            'Villa de San Antonio',
            'Las Lajas',
            'Taulabé'
        ]
    },
    {
        nombre: 'Copán',
        municipios: [
            'Santa Rosa de Copán',
            'Cabañas',
            'Concepción',
            'Copán Ruinas',
            'Corquín',
            'Dolores',
            'Dulce Nombre',
            'El Paraíso',
            'Florida',
            'La Jigua',
            'La Unión',
            'Nueva Arcadia',
            'San Agustín',
            'San Antonio',
            'San Jerónimo',
            'San José',
            'San Juan de Opoa',
            'San Nicolás',
            'San Pedro',
            'Santa Rita',
            'Trinidad de Copán',
            'Veracruz'
        ]
    },
    {
        nombre: 'Cortés',
        municipios: [
            'San Pedro Sula',
            'Choloma',
            'Omoa',
            'Pimienta',
            'Potrerillos',
            'Puerto Cortés',
            'San Antonio de Cortés',
            'San Francisco de Yojoa',
            'San Manuel',
            'Santa Cruz de Yojoa',
            'Villanueva',
            'La Lima'
        ]
    },
    {
        nombre: 'El Paraíso',
        municipios: [
            'Yuscarán',
            'Alauca',
            'Danlí',
            'El Paraíso',
            'Güinope',
            'Jacaleapa',
            'Liure',
            'Morocelí',
            'Oropolí',
            'Potrerillos',
            'San Antonio de Flores',
            'San Lucas',
            'San Matías',
            'Soledad',
            'Teupasenti',
            'Texiguat',
            'Vado Ancho',
            'Yauyupe',
            'Trojes'
        ]
    },
    {
        nombre: 'Francisco Morazán',
        municipios: [
            'Distrito Central (Comayagüela y Tegucigalpa)',
            'Alubarén',
            'Cedros',
            'Curarén',
            'El Porvenir',
            'Guaimaca',
            'La Libertad',
            'La Venta',
            'Lepaterique',
            'Maraita',
            'Marale',
            'Nueva Armenia',
            'Ojojona',
            'Orica',
            'Reitoca',
            'Sabanagrande',
            'San Antonio de Oriente',
            'San Buenaventura',
            'San Ignacio',
            'San Juan de Flores',
            'San Miguelito',
            'Santa Ana',
            'Santa Lucía',
            'Talanga',
            'Tatumbla',
            'Valle de Ángeles',
            'Villa de San Francisco',
            'Vallecillo'
        ]
    },
    {
        nombre: 'Gracias a Dios',
        municipios: [
            'Puerto Lempira',
            'Brus Laguna',
            'Ahuas',
            'Juan Francisco Bulnes',
            'Ramón Villeda Morales',
            'Wampusirpe',
        ]
    },
    {
        nombre: 'Intibucá',
        municipios: [
            'La Esperanza',
            'Camasca',
            'Colomoncagua',
            'Concepción',
            'Dolores',
            'Intibucá',
            'Jesús de Otoro',
            'Magdalena',
            'Masaguara',
            'San Antonio',
            'San Isidro',
            'San Juan',
            'San Marcos de la Sierra',
            'San Miguelito',
            'Santa Lucía',
            'Yamaranguila',
            'San Francisco de Opalaca'
        ]
    },
    {
        nombre: 'Islas de la Bahía',
        municipios: [
            'Roatán',
            'Guanaja',
            'José Santos Guardiola',
            'Utila'
        ]
    },
    {
        nombre: 'La Paz',
        municipios: [
            'La Paz',
            'Aguanqueterique',
            'Cabañas',
            'Cane',
            'Chinacla',
            'Guajiquiro',
            'Lauterique',
            'Marcala',
            'Mercedes de Oriente',
            'Opatoro',
            'San Antonio del Norte',
            'San José',
            'San Juan',
            'San Pedro de Tutule',
            'Santa Ana',
            'Santa Elena',
            'Santa María',
            'Santiago de Puringla',
            'Yarula'
        ]
    },
    {
        nombre: 'Lempira',
        municipios: [
            'Gracias',
            'Belén',
            'Candelaria',
            'Cololaca',
            'Erandique',
            'Gualcince',
            'Guarita',
            'La Campa',
            'La Iguala',
            'Las Flores',
            'La Unión',
            'La Virtud',
            'Lepaera',
            'Mapulaca',
            'Piraera',
            'San Andrés',
            'San Francisco',
            'San Juan Guarita',
            'San Manuel Colohete',
            'San Rafael',
            'San Sebastián',
            'Santa Cruz',
            'Talgua',
            'Tambla',
            'Tomalá',
            'Valladolid',
            'Virginia',
            'San Marcos de Caiquín'
        ]
    },
    {
        nombre: 'Ocotepeque',
        municipios: [
            'Ocotepeque',
            'Belén Gualcho',
            'Concepción',
            'Dolores Merendón',
            'Fraternidad',
            'La Encarnación',
            'La Labor',
            'Lucerna',
            'Mercedes',
            'San Fernando',
            'San Francisco del Valle',
            'San Jorge',
            'San Marcos',
            'Santa Fe',
            'Sensenti',
            'Sinuapa'
        ]
    },
    {
        nombre: 'Olancho',
        municipios: [
            'Juticalpa',
            'Campamento',
            'Catacamas',
            'Concordia',
            'Dulce Nombre de Culmí',
            'El Rosario',
            'Esquipulas del Norte',
            'Gualaco',
            'Guarizama',
            'Guata',
            'Guayape',
            'Jano',
            'La Unión',
            'Mangulile',
            'Manto',
            'Salamá',
            'San Esteban',
            'San Francisco de Becerra',
            'San Francisco de la Paz',
            'Santa María del Real',
            'Silca',
            'Yocón',
            'Patuca'
        ]
    },
    {
        nombre: 'Santa Bárbara', 
        municipios: [
            'Santa Bárbara',
            'Arada',
            'Atima',
            'Azacualpa',
            'Ceguaca',
            'Concepción del Norte',
            'Concepción del Sur',
            'Chinda',
            'El Níspero',
            'Gualala',
            'Ilama',
            'Las Vegas',
            'Macuelizo',
            'Naranjito',
            'Nuevo Celilac',
            'Nueva Frontera',
            'Petoa',
            'Protección',
            'Quimistán',
            'San Francisco de Ojuera',
            'San José de las Colinas',
            'San Luis',
            'San Marcos',
            'San Nicolás',
            'San Pedro Zacapa',
            'San Vicente Centenario',
            'Santa Rita',
            'Trinidad'
        ]
    },
    {
        nombre: 'Valle',
        municipios: [
            'Nacaome',
            'Alianza',
            'Amapala',
            'Aramecina',
            'Caridad',
            'Goascorán',
            'Langue',
            'San Francisco de Coray',
            'San Lorenzo'
        ]
    },
    {
        nombre: 'Yoro',
        municipios: [
            'Yoro',
            'Arenal',
            'El Negrito',
            'El Progreso',
            'Jocón',
            'Morazán',
            'Olanchito',
            'Santa Rita',
            'Sulaco',
            'Victoria',
            'Yorito'
        ]
    } 
]

export default Departamentos